"use client";

import { useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import jsPDF from "jspdf";
import {
  Baby,
  Briefcase,
  CheckCircle2,
  ClipboardCopy,
  Download,
  FileText,
  Flame,
  Gavel,
  LayoutList,
  ListTodo,
  Loader2,
  NotebookPen,
  Quote,
  RefreshCw,
  SmilePlus,
  Sparkles,
  Swords,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { useToast } from "@/hooks/use-toast";

type ModeValue =
  | "Action Items Only"
  | "Decisions Made"
  | "Brutal Roast"
  | "Executive Brief"
  | "Full Breakdown"
  | "Key Quotes"
  | "Sentiment Analysis"
  | "ELI5"
  | "SWOT Analysis"
  | "Meeting Minutes";

interface SummarizerOutputProps {
  result: string;
  mode: ModeValue;
  isLoading: boolean;
  error?: string;
  showSuccess?: boolean;
  onRegenerate?: (newMode: ModeValue) => void;
  onRetry?: () => void;
}

const MODE_CONFIG: Record<
  ModeValue,
  { color: string; bgColor: string; icon: React.ComponentType<{ className?: string }> }
> = {
  "Action Items Only": { color: "text-cyan-400", bgColor: "bg-cyan-500/10 border-cyan-500/30", icon: ListTodo },
  "Decisions Made": { color: "text-red-400", bgColor: "bg-red-500/10 border-red-500/30", icon: Gavel },
  "Brutal Roast": { color: "text-orange-400", bgColor: "bg-orange-500/10 border-orange-500/30", icon: Flame },
  "Executive Brief": { color: "text-purple-400", bgColor: "bg-purple-500/10 border-purple-500/30", icon: Briefcase },
  "Full Breakdown": { color: "text-green-400", bgColor: "bg-green-500/10 border-green-500/30", icon: LayoutList },
  "Key Quotes": { color: "text-pink-400", bgColor: "bg-pink-500/10 border-pink-500/30", icon: Quote },
  "Sentiment Analysis": { color: "text-yellow-400", bgColor: "bg-yellow-500/10 border-yellow-500/30", icon: SmilePlus },
  "ELI5": { color: "text-blue-400", bgColor: "bg-blue-500/10 border-blue-500/30", icon: Baby },
  "SWOT Analysis": { color: "text-indigo-400", bgColor: "bg-indigo-500/10 border-indigo-500/30", icon: Swords },
  "Meeting Minutes": { color: "text-teal-400", bgColor: "bg-teal-500/10 border-teal-500/30", icon: NotebookPen },
};

const ALL_MODES: ModeValue[] = [
  "Action Items Only",
  "Decisions Made",
  "Brutal Roast",
  "Executive Brief",
  "Full Breakdown",
  "Key Quotes",
  "Sentiment Analysis",
  "ELI5",
  "SWOT Analysis",
  "Meeting Minutes",
];

export function SummarizerOutput({
  result,
  mode,
  isLoading,
  error,
  showSuccess,
  onRegenerate,
  onRetry,
}: SummarizerOutputProps) {
  const { toast } = useToast();
  const [copying, setCopying] = useState(false);
  const [downloading, setDownloading] = useState(false);

  const modeConfig = MODE_CONFIG[mode];
  const ModeIcon = modeConfig.icon;

  const handleCopy = async () => {
    setCopying(true);
    try {
      await navigator.clipboard.writeText(result);
      toast({
        title: "Copied to clipboard!",
        description: "The summary has been copied to your clipboard.",
      });
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Copy failed",
        description: "Could not copy to clipboard. Please try again.",
      });
    } finally {
      setCopying(false);
    }
  };

  const handleDownloadTxt = () => {
    setDownloading(true);
    try {
      const content = `CLARIO SUMMARY REPORT\n\nSummary Mode: ${mode}\nGenerated: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}\n\n---\n\n${result}\n\n---\n\nGenerated by Clario Summarizer`;
      
      const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `Clario-Summary-${mode.replace(/\s+/g, "-")}-${new Date().toISOString().slice(0, 10)}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      toast({
        title: "Downloaded!",
        description: "Summary saved as TXT file.",
      });
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Download failed",
        description: "Could not download file. Please try again.",
      });
    } finally {
      setDownloading(false);
    }
  };

  const handleDownloadMd = () => {
    setDownloading(true);
    try {
      const content = `# CLARIO SUMMARY REPORT\n\n**Summary Mode:** ${mode}\n**Generated:** ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}\n\n---\n\n${result}\n\n---\n\n*Generated by Clario Summarizer*`;
      
      const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `Clario-Summary-${mode.replace(/\s+/g, "-")}-${new Date().toISOString().slice(0, 10)}.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      toast({
        title: "Downloaded!",
        description: "Summary saved as Markdown file.",
      });
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Download failed",
        description: "Could not download file. Please try again.",
      });
    } finally {
      setDownloading(false);
    }
  };

  const handleDownloadPdf = () => {
    setDownloading(true);
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      const maxWidth = pageWidth - 2 * margin;
      let yPosition = 20;

      doc.setFontSize(18);
      doc.text("CLARIO SUMMARY REPORT", margin, yPosition);
      yPosition += 10;

      doc.setFontSize(10);
      doc.text(`Mode: ${mode}`, margin, yPosition);
      yPosition += 6;
      doc.text(`Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, margin, yPosition);
      yPosition += 10;

      doc.setFontSize(11);
      const lines = doc.splitTextToSize(result, maxWidth);
      lines.forEach((line: string) => {
        if (yPosition > 280) {
          doc.addPage();
          yPosition = 20;
        }
        doc.text(line, margin, yPosition);
        yPosition += 6;
      });

      doc.save(`Clario-Summary-${mode.replace(/\s+/g, "-")}-${new Date().toISOString().slice(0, 10)}.pdf`);

      toast({
        title: "Downloaded!",
        description: "Summary saved as PDF file.",
      });
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Download failed",
        description: "Could not download PDF. Please try again.",
      });
    } finally {
      setDownloading(false);
    }
  };

  // Loading state
  if (isLoading) {
    return (
      <div className="mt-8">
        <Card className="bg-gradient-to-br from-[#0a0a0a] via-[#1a1a2e] to-[#0a0a0a] border-white/10">
          <CardContent className="p-6 sm:p-10">
            <div className="space-y-4 animate-pulse">
              <div className="h-8 bg-white/5 rounded w-3/4"></div>
              <div className="h-4 bg-white/5 rounded w-full"></div>
              <div className="h-4 bg-white/5 rounded w-5/6"></div>
              <div className="h-4 bg-white/5 rounded w-4/5"></div>
              <div className="h-8 bg-white/5 rounded w-2/3 mt-6"></div>
              <div className="h-4 bg-white/5 rounded w-full"></div>
              <div className="h-4 bg-white/5 rounded w-3/4"></div>
            </div>
            <div className="flex items-center justify-center mt-8 gap-2 text-[#4169E1]">
              <Loader2 className="h-5 w-5 animate-spin" />
              <span className="text-sm">Generating your summary...</span>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  // Error state
  if (error) {
    return (
      <div className="mt-8">
        <Card className="bg-red-500/10 border-red-500/30">
          <CardContent className="p-6 text-center">
            <p className="text-red-400 font-semibold mb-4">{error}</p>
            <Button
              variant="outline"
              onClick={onRetry || (() => window.location.reload())}
              className="border-red-500/30 text-red-400 hover:bg-red-500/10"
            >
              <RefreshCw className="mr-2 h-4 w-4" />
              Retry
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  // Empty state
  if (!result) {
    return (
      <div className="mt-8 text-center text-gray-400 py-12">
        <Sparkles className="h-12 w-12 mx-auto mb-4 text-[#4169E1]" />
        <p className="text-base">Your summary will appear here</p>
        <p className="text-sm mt-2 text-gray-500">
          Enter text and select a summary mode to get started
        </p>
      </div>
    );
  }

  // Success state with result
  return (
    <div className="mt-8">
      {/* Mode Badge */}
      <div className="flex items-center gap-3 mb-4">
        <div className={`flex items-center gap-2 px-4 py-2 rounded-lg border ${modeConfig.bgColor}`}>
          <ModeIcon className={`h-4 w-4 ${modeConfig.color}`} />
          <span className={`text-sm font-semibold ${modeConfig.color}`}>{mode}</span>
        </div>
        {showSuccess && (
          <CheckCircle2 className="h-6 w-6 text-[#4169E1] animate-in fade-in zoom-in" />
        )}
      </div>

      {/* Actions Bar */}
      <div className="flex flex-wrap gap-2 mb-4">
        <Button
          variant="outline"
          size="sm"
          onClick={handleCopy}
          disabled={copying}
          className="border-white/20 text-white hover:bg-white/10 min-h-[44px] min-w-[44px]"
        >
          {copying ? (
            <Loader2 className="mr-0 sm:mr-2 h-4 w-4 animate-spin" />
          ) : (
            <ClipboardCopy className="mr-0 sm:mr-2 h-4 w-4 text-[#4169E1]" />
          )}
          <span className="hidden sm:inline">Copy</span>
        </Button>
        
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button
              variant="outline"
              size="sm"
              disabled={downloading}
              className="border-white/20 text-white hover:bg-white/10 min-h-[44px]"
            >
              <Download className="mr-0 sm:mr-2 h-4 w-4 text-[#4169E1]" />
              <span className="hidden sm:inline">Download</span>
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent className="bg-[#1a1a2e] border-white/20">
            <DropdownMenuItem onClick={handleDownloadPdf} className="text-white hover:bg-white/10 cursor-pointer">
              <FileText className="mr-2 h-4 w-4 text-[#4169E1]" />
              PDF
            </DropdownMenuItem>
            <DropdownMenuItem onClick={handleDownloadMd} className="text-white hover:bg-white/10 cursor-pointer">
              <FileText className="mr-2 h-4 w-4 text-[#4169E1]" />
              Markdown
            </DropdownMenuItem>
            <DropdownMenuItem onClick={handleDownloadTxt} className="text-white hover:bg-white/10 cursor-pointer">
              <FileText className="mr-2 h-4 w-4 text-[#4169E1]" />
              Text
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>

        {onRegenerate && (
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                variant="outline"
                size="sm"
                className="border-white/20 text-white hover:bg-white/10 min-h-[44px]"
              >
                <RefreshCw className="mr-0 sm:mr-2 h-4 w-4 text-[#4169E1]" />
                <span className="hidden sm:inline">Regenerate</span>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent className="bg-[#1a1a2e] border-white/20 max-h-[300px] overflow-y-auto">
              {ALL_MODES.filter(m => m !== mode).map((m) => (
                <DropdownMenuItem
                  key={m}
                  onClick={() => onRegenerate(m)}
                  className="text-white hover:bg-white/10 cursor-pointer"
                >
                  {m}
                </DropdownMenuItem>
              ))}
            </DropdownMenuContent>
          </DropdownMenu>
        )}
      </div>

      {/* Summary Content */}
      <Card className="bg-gradient-to-br from-[#0a0a0a] via-[#1a1a2e] to-[#0a0a0a] border-white/10 shadow-2xl relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-[#4169E1]/5 via-transparent to-[#4169E1]/5 pointer-events-none"></div>
        <CardContent className="p-0 relative z-10">
          <div className="summary-prose p-4 sm:p-6 md:p-10 max-w-[800px] mx-auto">
            <ReactMarkdown
              remarkPlugins={[remarkGfm]}
              components={{
                h1: ({ children }) => <h1 className="text-2xl sm:text-3xl md:text-4xl">{children}</h1>,
                h2: ({ children }) => <h2 className="text-xl sm:text-2xl md:text-3xl">{children}</h2>,
                h3: ({ children }) => <h3 className="text-lg sm:text-xl md:text-2xl">{children}</h3>,
                h4: ({ children }) => <h4 className="text-base sm:text-lg md:text-xl">{children}</h4>,
                p: ({ children }) => <p className="text-sm sm:text-base leading-relaxed">{children}</p>,
                li: ({ children }) => <li className="text-sm sm:text-base">{children}</li>,
                code: ({ inline, children, ...props }: any) =>
                  inline ? (
                    <code {...props}>{children}</code>
                  ) : (
                    <pre className="overflow-x-auto">
                      <code {...props}>{children}</code>
                    </pre>
                  ),
              }}
            >
              {result}
            </ReactMarkdown>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
