"use client";

import { useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import jsPDF from "jspdf";
import {
  Baby,
  Briefcase,
  CheckCircle2,
  ClipboardCopy,
  Download,
  FileText,
  Flame,
  Gavel,
  History,
  LayoutList,
  ListTodo,
  Loader2,
  NotebookPen,
  Quote,
  RefreshCw,
  SmilePlus,
  Sparkles,
  Swords,
  Trash2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { useToast } from "@/hooks/use-toast";

type ModeValue =
  | "Action Items Only"
  | "Decisions Made"
  | "Brutal Roast"
  | "Executive Brief"
  | "Full Breakdown"
  | "Key Quotes"
  | "Sentiment Analysis"
  | "ELI5"
  | "SWOT Analysis"
  | "Meeting Minutes";

interface SummarizerOutputProps {
  result: string;
  mode: ModeValue;
  isLoading: boolean;
  error?: string;
  showSuccess?: boolean;
  onRegenerate?: (newMode: ModeValue) => void;
  onRetry?: () => void;
  history?: Array<{ id: string; text: string; mode: string; summary: string; timestamp: number }>;
  showHistory?: boolean;
  onToggleHistory?: () => void;
  onLoadFromHistory?: (entry: any) => void;
  onDeleteHistory?: (id: string) => void;
  onSummarize?: () => void;
  canSummarize?: boolean;
}

const MODE_CONFIG: Record<
  ModeValue,
  { color: string; bgColor: string; icon: React.ComponentType<{ className?: string }> }
> = {
  "Action Items Only": { color: "text-cyan-400", bgColor: "bg-cyan-500/10 border-cyan-500/30", icon: ListTodo },
  "Decisions Made": { color: "text-red-400", bgColor: "bg-red-500/10 border-red-500/30", icon: Gavel },
  "Brutal Roast": { color: "text-orange-400", bgColor: "bg-orange-500/10 border-orange-500/30", icon: Flame },
  "Executive Brief": { color: "text-purple-400", bgColor: "bg-purple-500/10 border-purple-500/30", icon: Briefcase },
  "Full Breakdown": { color: "text-green-400", bgColor: "bg-green-500/10 border-green-500/30", icon: LayoutList },
  "Key Quotes": { color: "text-pink-400", bgColor: "bg-pink-500/10 border-pink-500/30", icon: Quote },
  "Sentiment Analysis": { color: "text-yellow-400", bgColor: "bg-yellow-500/10 border-yellow-500/30", icon: SmilePlus },
  "ELI5": { color: "text-blue-400", bgColor: "bg-blue-500/10 border-blue-500/30", icon: Baby },
  "SWOT Analysis": { color: "text-indigo-400", bgColor: "bg-indigo-500/10 border-indigo-500/30", icon: Swords },
  "Meeting Minutes": { color: "text-teal-400", bgColor: "bg-teal-500/10 border-teal-500/30", icon: NotebookPen },
};

const ALL_MODES: ModeValue[] = [
  "Action Items Only",
  "Decisions Made",
  "Brutal Roast",
  "Executive Brief",
  "Full Breakdown",
  "Key Quotes",
  "Sentiment Analysis",
  "ELI5",
  "SWOT Analysis",
  "Meeting Minutes",
];

export function SummarizerOutput({
  result,
  mode,
  isLoading,
  error,
  showSuccess,
  onRegenerate,
  onRetry,
  history = [],
  showHistory = false,
  onToggleHistory,
  onLoadFromHistory,
  onDeleteHistory,
  onSummarize,
  canSummarize = false,
}: SummarizerOutputProps) {
  const { toast } = useToast();
  const [copying, setCopying] = useState(false);
  const [downloading, setDownloading] = useState(false);

  const modeConfig = MODE_CONFIG[mode];
  const ModeIcon = modeConfig.icon;

  const handleCopy = async () => {
    setCopying(true);
    try {
      await navigator.clipboard.writeText(result);
      toast({
        title: "Copied to clipboard!",
        description: "The summary has been copied to your clipboard.",
      });
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Copy failed",
        description: "Could not copy to clipboard. Please try again.",
      });
    } finally {
      setCopying(false);
    }
  };

  const handleDownloadTxt = () => {
    setDownloading(true);
    try {
      const content = `CLARIO SUMMARY REPORT\n\nSummary Mode: ${mode}\nGenerated: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}\n\n---\n\n${result}\n\n---\n\nGenerated by Clario Summarizer`;
      
      const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `Clario-Summary-${mode.replace(/\s+/g, "-")}-${new Date().toISOString().slice(0, 10)}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      toast({
        title: "Downloaded!",
        description: "Summary saved as TXT file.",
      });
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Download failed",
        description: "Could not download file. Please try again.",
      });
    } finally {
      setDownloading(false);
    }
  };

  const handleDownloadMd = () => {
    setDownloading(true);
    try {
      const content = `# CLARIO SUMMARY REPORT\n\n**Summary Mode:** ${mode}\n**Generated:** ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}\n\n---\n\n${result}\n\n---\n\n*Generated by Clario Summarizer*`;
      
      const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `Clario-Summary-${mode.replace(/\s+/g, "-")}-${new Date().toISOString().slice(0, 10)}.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      toast({
        title: "Downloaded!",
        description: "Summary saved as Markdown file.",
      });
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Download failed",
        description: "Could not download file. Please try again.",
      });
    } finally {
      setDownloading(false);
    }
  };

  const handleDownloadPdf = () => {
    setDownloading(true);
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const maxWidth = pageWidth - 2 * margin;
      let yPosition = 20;

      // Helper to add new page if needed
      const checkPageBreak = (requiredSpace: number) => {
        if (yPosition + requiredSpace > pageHeight - margin) {
          doc.addPage();
          yPosition = margin;
          return true;
        }
        return false;
      };

      // Header
      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      doc.text("CLARIO SUMMARY REPORT", margin, yPosition);
      yPosition += 10;

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(`Mode: ${mode}`, margin, yPosition);
      yPosition += 6;
      doc.text(`Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, margin, yPosition);
      yPosition += 12;

      // Parse and format markdown content
      const lines = result.split('\n');
      
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        
        // Skip empty lines but add spacing
        if (!line.trim()) {
          yPosition += 4;
          continue;
        }

        // H1 headers (# )
        if (line.startsWith('# ')) {
          checkPageBreak(15);
          doc.setFontSize(16);
          doc.setFont("helvetica", "bold");
          const text = line.replace(/^#\s+/, '');
          doc.text(text, margin, yPosition);
          yPosition += 12;
          continue;
        }

        // H2 headers (## )
        if (line.startsWith('## ')) {
          checkPageBreak(12);
          doc.setFontSize(14);
          doc.setFont("helvetica", "bold");
          const text = line.replace(/^##\s+/, '');
          doc.text(text, margin, yPosition);
          yPosition += 10;
          continue;
        }

        // H3 headers (### )
        if (line.startsWith('### ')) {
          checkPageBreak(10);
          doc.setFontSize(12);
          doc.setFont("helvetica", "bold");
          const text = line.replace(/^###\s+/, '');
          doc.text(text, margin, yPosition);
          yPosition += 8;
          continue;
        }

        // H4 headers (#### )
        if (line.startsWith('#### ')) {
          checkPageBreak(8);
          doc.setFontSize(11);
          doc.setFont("helvetica", "bold");
          const text = line.replace(/^####\s+/, '');
          doc.text(text, margin, yPosition);
          yPosition += 7;
          continue;
        }

        // Blockquotes (> )
        if (line.startsWith('> ')) {
          checkPageBreak(8);
          doc.setFontSize(10);
          doc.setFont("helvetica", "italic");
          const text = line.replace(/^>\s+/, '');
          const cleanText = text.replace(/\*\*(.*?)\*\*/g, '$1').replace(/\*(.*?)\*/g, '$1');
          const wrappedLines = doc.splitTextToSize(cleanText, maxWidth - 10);
          doc.text(wrappedLines, margin + 5, yPosition);
          yPosition += wrappedLines.length * 6 + 2;
          continue;
        }

        // Horizontal rules (--- or ***)
        if (line.match(/^[-*]{3,}$/)) {
          checkPageBreak(5);
          yPosition += 3;
          continue;
        }

        // Bullet points (- or * )
        if (line.match(/^[\s]*[-*]\s+/)) {
          checkPageBreak(8);
          doc.setFontSize(11);
          doc.setFont("helvetica", "normal");
          const indent = (line.match(/^\s*/)?.[0].length || 0) / 2;
          const text = line.replace(/^[\s]*[-*]\s+/, '');
          const cleanText = text.replace(/\*\*(.*?)\*\*/g, '$1').replace(/\*(.*?)\*/g, '$1');
          const wrappedLines = doc.splitTextToSize(cleanText, maxWidth - (indent * 5) - 10);
          doc.text('•', margin + (indent * 5), yPosition);
          doc.text(wrappedLines, margin + (indent * 5) + 5, yPosition);
          yPosition += wrappedLines.length * 6;
          continue;
        }

        // Numbered lists (1. 2. etc)
        if (line.match(/^[\s]*\d+\.\s+/)) {
          checkPageBreak(8);
          doc.setFontSize(11);
          doc.setFont("helvetica", "normal");
          const indent = (line.match(/^\s*/)?.[0].length || 0) / 2;
          const number = line.match(/\d+\./)?.[0] || '';
          const text = line.replace(/^[\s]*\d+\.\s+/, '');
          const cleanText = text.replace(/\*\*(.*?)\*\*/g, '$1').replace(/\*(.*?)\*/g, '$1');
          const wrappedLines = doc.splitTextToSize(cleanText, maxWidth - (indent * 5) - 15);
          doc.text(number, margin + (indent * 5), yPosition);
          doc.text(wrappedLines, margin + (indent * 5) + 10, yPosition);
          yPosition += wrappedLines.length * 6;
          continue;
        }

        // Regular paragraphs
        checkPageBreak(8);
        doc.setFontSize(11);
        doc.setFont("helvetica", "normal");
        const cleanText = line.replace(/\*\*(.*?)\*\*/g, '$1').replace(/\*(.*?)\*/g, '$1');
        const wrappedLines = doc.splitTextToSize(cleanText, maxWidth);
        doc.text(wrappedLines, margin, yPosition);
        yPosition += wrappedLines.length * 6 + 2;
      }

      doc.save(`Clario-Summary-${mode.replace(/\s+/g, "-")}-${new Date().toISOString().slice(0, 10)}.pdf`);

      toast({
        title: "Downloaded!",
        description: "Summary saved as PDF file.",
      });
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Download failed",
        description: "Could not download PDF. Please try again.",
      });
    } finally {
      setDownloading(false);
    }
  };

  // Loading state
  if (isLoading) {
    return (
      <div className="mt-8">
        <Card className="bg-gradient-to-br from-[#0a0a0a] via-[#1a1a2e] to-[#0a0a0a] border-white/10">
          <CardContent className="p-6 sm:p-10">
            <div className="space-y-4 animate-pulse">
              <div className="h-8 bg-white/5 rounded w-3/4"></div>
              <div className="h-4 bg-white/5 rounded w-full"></div>
              <div className="h-4 bg-white/5 rounded w-5/6"></div>
              <div className="h-4 bg-white/5 rounded w-4/5"></div>
              <div className="h-8 bg-white/5 rounded w-2/3 mt-6"></div>
              <div className="h-4 bg-white/5 rounded w-full"></div>
              <div className="h-4 bg-white/5 rounded w-3/4"></div>
            </div>
            <div className="flex items-center justify-center mt-8 gap-2 text-[#4169E1]">
              <Loader2 className="h-5 w-5 animate-spin" />
              <span className="text-sm">Generating your summary...</span>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  // Error state
  if (error) {
    return (
      <div className="mt-8">
        <Card className="bg-red-500/10 border-red-500/30">
          <CardContent className="p-6 text-center">
            <p className="text-red-400 font-semibold mb-4">{error}</p>
            <Button
              variant="outline"
              onClick={onRetry || (() => window.location.reload())}
              className="border-red-500/30 text-red-400 hover:bg-red-500/10"
            >
              <RefreshCw className="mr-2 h-4 w-4" />
              Retry
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  // Empty state
  if (!result) {
    return (
      <div className="mt-8">
        {/* Actions Bar */}
        <div className="flex flex-wrap justify-center gap-2 mb-4">
          <Button
            variant="outline"
            size="sm"
            onClick={onToggleHistory}
            disabled={history.length === 0}
            className="border-white/20 text-white hover:bg-white/10 min-h-[44px]"
          >
            <History className="mr-0 sm:mr-2 h-4 w-4 text-[#4169E1]" />
            <span className="hidden sm:inline">History ({history.length})</span>
          </Button>
          
          <Button
            variant="outline"
            size="sm"
            disabled
            className="border-white/20 text-white hover:bg-white/10 min-h-[44px] min-w-[44px] opacity-50 cursor-not-allowed"
          >
            <ClipboardCopy className="mr-0 sm:mr-2 h-4 w-4 text-[#4169E1]" />
            <span className="hidden sm:inline">Copy</span>
          </Button>
          
          <Button
            variant="outline"
            size="sm"
            onClick={onSummarize}
            disabled={!canSummarize || isLoading}
            className="border-white/20 text-white hover:bg-white/10 min-h-[44px]"
          >
            {isLoading ? (
              <Loader2 className="mr-0 sm:mr-2 h-4 w-4 animate-spin" />
            ) : (
              <Sparkles className="mr-0 sm:mr-2 h-4 w-4 text-[#4169E1]" />
            )}
            <span className="hidden sm:inline">Summarize</span>
          </Button>
          
          <Button
            variant="outline"
            size="sm"
            disabled
            className="border-white/20 text-white hover:bg-white/10 min-h-[44px] opacity-50 cursor-not-allowed"
          >
            <Download className="mr-0 sm:mr-2 h-4 w-4 text-[#4169E1]" />
            <span className="hidden sm:inline">Download</span>
          </Button>

          <Button
            variant="outline"
            size="sm"
            disabled
            className="border-white/20 text-white hover:bg-white/10 min-h-[44px] opacity-50 cursor-not-allowed"
          >
            <RefreshCw className="mr-0 sm:mr-2 h-4 w-4 text-[#4169E1]" />
            <span className="hidden sm:inline">Regenerate</span>
          </Button>
        </div>

        <div className="text-center text-gray-400 py-12">
          <Sparkles className="h-12 w-12 mx-auto mb-4 text-[#4169E1]" />
          <p className="text-base">Your summary will appear here</p>
          <p className="text-sm mt-2 text-gray-500">
            Enter text and select a summary mode to get started
          </p>
        </div>
      </div>
    );
  }

  // Success state with result
  return (
    <div className="mt-8 space-y-4">
      {/* Mode Badge & Actions */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-4 rounded-xl bg-gradient-to-r from-[#4169E1]/10 to-purple-500/10 border border-[#4169E1]/20">
        <div className="flex items-center gap-3">
          <div className={`p-2 rounded-lg ${modeConfig.bgColor}`}>
            <ModeIcon className={`h-5 w-5 ${modeConfig.color}`} />
          </div>
          <div>
            <h3 className="text-sm font-semibold text-white">{mode}</h3>
            <p className="text-xs text-gray-400">Generated {new Date().toLocaleTimeString()}</p>
          </div>
        </div>
        
        <div className="flex flex-wrap gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={onToggleHistory}
            disabled={history.length === 0}
            className="border-white/20 text-white hover:bg-white/10"
          >
            <History className="mr-2 h-4 w-4" />
            {history.length}
          </Button>
          
          <Button
            variant="outline"
            size="sm"
            onClick={handleCopy}
            disabled={copying}
            className="border-white/20 text-white hover:bg-white/10"
          >
            {copying ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <ClipboardCopy className="mr-2 h-4 w-4" />}
            Copy
          </Button>
          
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline" size="sm" disabled={downloading} className="border-white/20 text-white hover:bg-white/10">
                <Download className="mr-2 h-4 w-4" />
                Export
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent className="bg-[#1a1a2e] border-white/20">
              <DropdownMenuItem onClick={handleDownloadPdf} className="text-white hover:bg-white/10 cursor-pointer">
                <FileText className="mr-2 h-4 w-4" /> PDF
              </DropdownMenuItem>
              <DropdownMenuItem onClick={handleDownloadMd} className="text-white hover:bg-white/10 cursor-pointer">
                <FileText className="mr-2 h-4 w-4" /> Markdown
              </DropdownMenuItem>
              <DropdownMenuItem onClick={handleDownloadTxt} className="text-white hover:bg-white/10 cursor-pointer">
                <FileText className="mr-2 h-4 w-4" /> Text
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>

          {onRegenerate && (
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="outline" size="sm" className="border-white/20 text-white hover:bg-white/10">
                  <RefreshCw className="mr-2 h-4 w-4" />
                  Change Mode
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent className="bg-[#1a1a2e] border-white/20 max-h-[300px] overflow-y-auto">
                {ALL_MODES.filter(m => m !== mode).map((m) => (
                  <DropdownMenuItem key={m} onClick={() => onRegenerate(m)} className="text-white hover:bg-white/10 cursor-pointer">
                    {m}
                  </DropdownMenuItem>
                ))}
              </DropdownMenuContent>
            </DropdownMenu>
          )}
        </div>
      </div>

      {/* Summary Content - New Modern Design */}
      <Card className="bg-gradient-to-br from-[#0f0f1a] via-[#1a1a2e] to-[#0f0f1a] border-[#4169E1]/20 shadow-2xl overflow-hidden">
        <CardContent className="p-0">
          <div className="summary-prose-modern p-6 sm:p-10 max-w-none text-gray-100">
            <ReactMarkdown 
              remarkPlugins={[remarkGfm]}
              components={{
                h1: ({node, ...props}) => <h1 className="text-3xl font-bold mb-6 pb-3 border-b border-[#4169E1]/30 bg-gradient-to-r from-white to-blue-200 bg-clip-text text-transparent" {...props} />,
                h2: ({node, ...props}) => <h2 className="text-2xl font-semibold mt-8 mb-4 text-white flex items-center gap-2" {...props} />,
                h3: ({node, ...props}) => <h3 className="text-xl font-semibold mt-6 mb-3 text-blue-200" {...props} />,
                h4: ({node, ...props}) => <h4 className="text-lg font-medium mt-4 mb-2 text-blue-300" {...props} />,
                p: ({node, ...props}) => <p className="mb-4 leading-relaxed text-gray-300" {...props} />,
                ul: ({node, ...props}) => <ul className="space-y-2 mb-4 ml-6" {...props} />,
                ol: ({node, ...props}) => <ol className="space-y-2 mb-4 ml-6" {...props} />,
                li: ({node, ...props}) => <li className="text-gray-300 leading-relaxed" {...props} />,
                blockquote: ({node, ...props}) => <blockquote className="border-l-4 border-[#4169E1] bg-[#4169E1]/5 pl-4 py-2 my-4 italic text-blue-100" {...props} />,
                strong: ({node, ...props}) => <strong className="font-semibold text-white" {...props} />,
                code: ({node, inline, ...props}: any) => 
                  inline ? 
                    <code className="bg-[#4169E1]/10 text-blue-300 px-1.5 py-0.5 rounded text-sm" {...props} /> : 
                    <code className="block bg-[#0a0a0a] text-green-300 p-4 rounded-lg my-4 overflow-x-auto" {...props} />,
                hr: ({node, ...props}) => <hr className="my-6 border-[#4169E1]/20" {...props} />,
                table: ({node, ...props}) => <div className="overflow-x-auto my-4"><table className="w-full border-collapse" {...props} /></div>,
                th: ({node, ...props}) => <th className="border border-[#4169E1]/30 bg-[#4169E1]/10 px-4 py-2 text-left font-semibold text-white" {...props} />,
                td: ({node, ...props}) => <td className="border border-[#4169E1]/20 px-4 py-2 text-gray-300" {...props} />,
              }}
            >
              {result}
            </ReactMarkdown>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
